### ISSUE TITLE
Cannot stop or "end" stream.

### ISSUE THREAD

**Issue by mikeal** [mafintosh/media-recorder-stream#2]
There's no `stop()` method (which is the verb used in the recorder object) and there's no `end()` method either (the verb for Node.js streams).

Additionally, if you call `stream.recorder.stop()` it's not picked up anywhere by the actual readable stream so it never emits and end event.

**Comment by mafintosh** [comment]
.destroy() doesn't work?

**Comment by mikeal** [comment]
I guess I could do that, but destroy is usually... destructive ;) The ergonomics seem a little weird, but this will work :)

**Comment by mafintosh** [comment]
Ah I see what you're getting at! We should add a finalize method to do what you want then.

**Comment by mikeal** [comment]
Another thing I'm wondering about, is there any delay after calling `recorder.stop()` where data continues to flush? https://github.com/mafintosh/media-recorder-stream/blob/master/index.js#L21

**Comment by mikeal** [comment]
The spec seems to insinuate that it calls the final data event synchronously https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder

**Comment by mafintosh** [comment]
Fixed by you!
